name: Generate RSS Feed (Simplified)

on:
  schedule:
    # Run every 6 hours (at 00:00, 06:00, 12:00, 18:00 UTC)
    - cron: '0 */6 * * *'
  workflow_dispatch: # Allow manual trigger
  push:
    branches: [ main ]
    paths:
      - 'scraper.py'
      - '.github/workflows/rss-generator.yml'

jobs:
  generate-rss:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write  # Allow writing to repository
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 lxml
        
    - name: Run RSS scraper
      env:
        RSS_OUTPUT_FILE: feed.xml
      run: |
        python scraper.py
        
    - name: Validate RSS feed
      run: |
        if [ ! -f feed.xml ]; then
          echo "RSS feed file not found!"
          exit 1
        fi
        
        # Check if file is not empty
        if [ ! -s feed.xml ]; then
          echo "RSS feed file is empty!"
          exit 1
        fi
        
        # Basic XML validation
        python -c "import xml.etree.ElementTree as ET; ET.parse('feed.xml')"
        echo "RSS feed validation passed!"
        
    - name: Display feed info
      run: |
        echo "RSS feed generated at: $(date)"
        echo "File size: $(du -h feed.xml | cut -f1)"
        echo "Number of items: $(grep -c '<item>' feed.xml || echo '0')"
        
    - name: Create simple index page
      run: |
        CURRENT_DATE=$(date '+%B %d, %Y at %H:%M UTC')
        cat > index.html << EOF
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Google Developers Search Blog RSS Feed</title>
            <style>
                body { 
                    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; 
                    max-width: 800px; 
                    margin: 50px auto; 
                    padding: 20px; 
                    line-height: 1.6;
                    color: #333;
                }
                .feed-link { 
                    background: #f8f9fa; 
                    padding: 20px; 
                    border-radius: 8px; 
                    margin: 20px 0; 
                    border-left: 4px solid #007bff;
                }
                .feed-url {
                    font-family: 'Monaco', 'Menlo', monospace;
                    background: #e9ecef;
                    padding: 8px 12px;
                    border-radius: 4px;
                    word-break: break-all;
                }
                .timestamp { 
                    color: #666; 
                    font-size: 0.9em; 
                    margin-top: 30px;
                    padding-top: 20px;
                    border-top: 1px solid #eee;
                }
                a { color: #007bff; text-decoration: none; }
                a:hover { text-decoration: underline; }
                .header { text-align: center; margin-bottom: 40px; }
                .instructions { background: #fff3cd; padding: 15px; border-radius: 5px; margin: 20px 0; }
            </style>
        </head>
        <body>
            <div class="header">
                <h1>🔍 Google Developers Search Blog RSS</h1>
                <p>Automatically generated RSS feed from the <a href="https://developers.googleblog.com/en/search/" target="_blank">Google Developers Search blog</a></p>
            </div>
            
            <div class="feed-link">
                <h3>📡 RSS Feed URL:</h3>
                <div class="feed-url">
                    <a href="feed.xml">https://lawvia.github.io/google-dev-rss/feed.xml</a>
                </div>
            </div>
            
            <div class="instructions">
                <h3>📚 How to use this RSS feed:</h3>
                <ol>
                    <li>Copy the RSS feed URL above</li>
                    <li>Open your favorite RSS reader (Feedly, Inoreader, Apple News, etc.)</li>
                    <li>Add a new subscription using the RSS URL</li>
                    <li>Enjoy automatic updates!</li>
                </ol>
            </div>
            
            <h3>⚡ Popular RSS Readers:</h3>
            <ul>
                <li><strong><a href="https://feedly.com" target="_blank">Feedly</a></strong> - Web-based, most popular</li>
                <li><strong><a href="https://www.inoreader.com" target="_blank">Inoreader</a></strong> - Feature-rich</li>
                <li><strong><a href="https://newsblur.com" target="_blank">NewsBlur</a></strong> - Social features</li>
                <li><strong>Apple News</strong> - Built into iOS/macOS</li>
                <li><strong>Thunderbird</strong> - Desktop email client</li>
            </ul>
            
            <h3>🔄 Update Schedule:</h3>
            <p>This feed updates automatically every 6 hours via GitHub Actions.</p>
            
            <div class="timestamp">
                ⏱️ Last updated: $CURRENT_DATE<br>
                🤖 Generated automatically via <a href="https://github.com/Lawvia/google-dev-rss" target="_blank">GitHub Actions</a>
            </div>
        </body>
        </html>
        EOF
        
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "RSS Bot"
        
        # Add timestamp to commit message
        TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S UTC')
        
        git add feed.xml index.html
        
        # Only commit if there are changes
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "🔄 Update RSS feed - $TIMESTAMP [skip ci]"
          git push
          echo "✅ RSS feed updated and pushed"
        fi
        
    - name: Upload RSS feed as artifact
      uses: actions/upload-artifact@v4
      with:
        name: rss-feed-${{ github.run_number }}
        path: |
          feed.xml
          index.html
        retention-days: 30
        
    - name: Summary
      run: |
        echo "## 📊 RSS Generation Summary" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ RSS Feed Generated: \`feed.xml\`" >> $GITHUB_STEP_SUMMARY
        echo "- 📄 Index Page Created: \`index.html\`" >> $GITHUB_STEP_SUMMARY
        echo "- 📈 Articles Found: $(grep -c '<item>' feed.xml || echo '0')" >> $GITHUB_STEP_SUMMARY
        echo "- 📦 File Size: $(du -h feed.xml | cut -f1)" >> $GITHUB_STEP_SUMMARY
        echo "- 🌐 Feed URL: [https://lawvia.github.io/google-dev-rss/feed.xml](https://lawvia.github.io/google-dev-rss/feed.xml)" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### 🔗 Quick Links" >> $GITHUB_STEP_SUMMARY
        echo "- [View RSS Feed](https://lawvia.github.io/google-dev-rss/feed.xml)" >> $GITHUB_STEP_SUMMARY
        echo "- [View Index Page](https://lawvia.github.io/google-dev-rss/)" >> $GITHUB_STEP_SUMMARY
        echo "- [Source Blog](https://developers.googleblog.com/en/search/)" >> $GITHUB_STEP_SUMMARY
